destination: ./_site
permalink: /:year/:month/:day/:title/
exclude: ["config.rb", "Gemfile", "Gemfile.lock", "Rakefile", "README.md", "assets/sass"]
plugins:
  - jekyll-paginate
  - jekyll-feed
timezone: Pacific/Honolulu
paginate: 3
markdown: kramdown

# The safe option seems to disable the jekyll plugins when it shouldn't be
# safe: true

title: "-:&[squeg.net)%."
description: v. to oscillate in a highly irregular fashion
url: http://squeg.net/
author: Bob Matcuk

